Repository xmldom/xmldom, pull requests merged in 2021-09, with the labels that each got.

#314 fix: Normalize all line endings
  lib/dom-parser.js
  test/dom/document.test.js
  test/get-test-parser.js
  test/parse/normalize-line-endings.test.js
  test/parse/test-doc-whitespace.test.js
Labels: breaking change

#304 ci(github): Split test and lint steps into jobs
  .github/workflows/test-node.js.yml
Labels: question, testing, code style, infrastructure

#321 fix(dom): Preserve default namespace when serializing
  lib/dom.js
  test/dom/serializer.test.js
Labels: spec:Namespaces in XML

#310 fix(XMLSerializer): Preserve whitespace character references
  lib/dom-parser.js
  lib/dom.js
  lib/sax.js
  test/dom/serializer.test.js
  test/parse/parse-element.test.js
  test/xmltest/__snapshots__/not-wf.test.js.snap
  test/xmltest/__snapshots__/valid.test.js.snap
Labels: breaking change
