Repository xmldom/xmldom, pull requests merged in 2021-08, with the labels that each got.

#279 chore(package.json): remove author, maintainers, etc.
  package.json
Labels: documentation

#288 fix(types): Add index.d.ts to packaged files
  package.json
Labels: types

#292 chore(stryker): Switch to dashboard owned by org
  readme.md
  stryker.conf.json
Labels: infrastructure

#300 test: Fix stryker config
  stryker.conf.json
Labels: testing

#307 fix: Normalize line breaks according to spec
  lib/dom-parser.js
  test/parse/__snapshots__/test-doc-whitespace.test.js.snap
  test/parse/test-doc-whitespace.test.js
  test/xmltest/__snapshots__/not-wf.test.js.snap
  test/xmltest/__snapshots__/valid.test.js.snap
Labels: spec:XML, breaking change
